=== Luizhen/sim104/trunk/lru.xsd
<?xml version="1.0" encoding="windows-1252" ?>
<xsd:schema targetNamespace="http://www.realtimesystems.es/sim104"
            elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:s104="http://www.realtimesystems.es/sim104" xmlns:xml="http://www.w3.org/XML/1998/namespace">
  <xsd:element name="LRU" xml:COMMADDRNUM="" xml:DEV_NAME="" xml:LRU_NAME=""
               xml:LRU_NO="" xml:RTU_IP_ADDR_STR="">
    <xsd:complexType>
      <xsd:sequence>

                <xsd:element name="SP"  maxOccurs="unbounded" minOccurs="0" type="s104:ScadaElement">


         </xsd:element>
                <xsd:element name="DP" maxOccurs="unbounded" minOccurs="0" type="s104:ScadaElement">
        </xsd:element>
        <xsd:element name="MS"  maxOccurs="unbounded" minOccurs="0" type="s104:ScadaElement">
        </xsd:element>
        <xsd:element name="ST" maxOccurs="unbounded" minOccurs="0" type="s104:ScadaElement">
        </xsd:element>
      </xsd:sequence>
      <xsd:attribute name="COMMADDRNUM"     use="required"     type="xsd:integer" />
      <xsd:attribute name="DEV_NAME"        use="required"     type="xsd:string"  />
      <xsd:attribute name="LRU_NAME"        use="required"     type="xsd:string"  />
      <xsd:attribute name="LRU_NO"          use="required"     type="xsd:integer" />
      <xsd:attribute name="RTU_IP_ADDR_STR" use="required"     type="xsd:string"  />
    </xsd:complexType>
  </xsd:element>


    <xsd:complexType name="ScadaElement">
     <xsd:attribute name="COMM_ADDRNUM" type="xsd:integer" />
            <xsd:attribute name="COMM_TYPE" type="xsd:string" />
            <xsd:attribute name="INFO_B1" type="xsd:string" />
            <xsd:attribute name="INFO_B2" type="xsd:string" />
            <xsd:attribute name="INFO_B3" type="xsd:string" />
            <xsd:attribute name="INFO_ELEM" type="xsd:string" />
            <xsd:attribute name="INFO_INFO" type="xsd:string" />
            <xsd:attribute name="MON_ADDRNUM" type="xsd:integer" />
            <xsd:attribute name="COM_TYPE" type="xsd:string" />
            <xsd:attribute name="COM_ADDRNUM" type="xsd:integer" />
            <xsd:attribute name="PRO_GC" type="xsd:string" />

    </xsd:complexType>
</xsd:schema>

=== Luizhen/sim104/SCONTROL.xml
<?xml version="1.0" encoding="UTF-8"?>
<s104:LRU LRU_NAME="SCONTROL" DEV_NAME="001-7-07" LRU_NO="2411" COMMADDRNUM="55999" RTU_IP_ADDR_STR="111.112.191.218"  xmlns:s104="http://www.realtimesystems.es/sim104" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.realtimesystems.es/sim104 lru.xsd ">
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl705" INFO_INFO="Estado" MON_ADDRNUM="10010" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl265" INFO_INFO="Estado" MON_ADDRNUM="10011" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl573" INFO_INFO="Estado" MON_ADDRNUM="10012" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl455" INFO_INFO="Estado" MON_ADDRNUM="10013" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl572" INFO_INFO="Estado" MON_ADDRNUM="10014" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl002" INFO_INFO="Estado" MON_ADDRNUM="10015" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl013" INFO_INFO="Estado" MON_ADDRNUM="10016" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl009" INFO_INFO="Estado" MON_ADDRNUM="10017" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="TrfAl092" INFO_INFO="Estado" MON_ADDRNUM="10018" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinAl014" INFO_INFO="Estado" MON_ADDRNUM="10019" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinAl015" INFO_INFO="Estado" MON_ADDRNUM="10020" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinAl016" INFO_INFO="Estado" MON_ADDRNUM="10021" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl008" INFO_INFO="Estado" MON_ADDRNUM="10022" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl003" INFO_INFO="Estado" MON_ADDRNUM="10023" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinAl017" INFO_INFO="Estado" MON_ADDRNUM="10024" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinAl511" INFO_INFO="Estado" MON_ADDRNUM="10025" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl435" INFO_INFO="Estado" MON_ADDRNUM="10026" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="BarAl414" INFO_INFO="Estado" MON_ADDRNUM="10027" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinAl009" INFO_INFO="Estado" MON_ADDRNUM="10028" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinAl520" INFO_INFO="Estado" MON_ADDRNUM="10029" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinAl536" INFO_INFO="Estado" MON_ADDRNUM="10030" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="SgnAl388" INFO_INFO="Estado" MON_ADDRNUM="10031" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinAl554" INFO_INFO="Estado" MON_ADDRNUM="10032" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinSt050" INFO_INFO="Estado" MON_ADDRNUM="10033" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl007" INFO_INFO="Estado" MON_ADDRNUM="10034" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl087" INFO_INFO="Estado" MON_ADDRNUM="10035" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinAl006" INFO_INFO="Estado" MON_ADDRNUM="10036" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl048" INFO_INFO="Estado" MON_ADDRNUM="10037" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinAl550" INFO_INFO="Estado" MON_ADDRNUM="10038" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinAl551" INFO_INFO="Estado" MON_ADDRNUM="10039" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="IntAl001" INFO_INFO="Estado" MON_ADDRNUM="10040" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinAl028" INFO_INFO="Estado" MON_ADDRNUM="10041" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="SICAl009" INFO_INFO="Estado" MON_ADDRNUM="10042" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="SgnAl390" INFO_INFO="Estado" MON_ADDRNUM="10043" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="C3IAl726" INFO_INFO="Estado" MON_ADDRNUM="10044" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="OLIVARES" INFO_ELEM="LinAl389" INFO_INFO="Estado" MON_ADDRNUM="10045" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="IntAl705" INFO_INFO="Estado" MON_ADDRNUM="10046" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="IntAl265" INFO_INFO="Estado" MON_ADDRNUM="10047" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="IntAl573" INFO_INFO="Estado" MON_ADDRNUM="10048" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="IntAl455" INFO_INFO="Estado" MON_ADDRNUM="10049" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="IntAl572" INFO_INFO="Estado" MON_ADDRNUM="10050" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="IntAl002" INFO_INFO="Estado" MON_ADDRNUM="10051" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="IntAl013" INFO_INFO="Estado" MON_ADDRNUM="10052" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="IntAl009" INFO_INFO="Estado" MON_ADDRNUM="10053" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="TrfAl092" INFO_INFO="Estado" MON_ADDRNUM="10054" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="LinAl014" INFO_INFO="Estado" MON_ADDRNUM="10055" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="LinAl015" INFO_INFO="Estado" MON_ADDRNUM="10056" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="LinAl016" INFO_INFO="Estado" MON_ADDRNUM="10057" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="IntAl008" INFO_INFO="Estado" MON_ADDRNUM="10058" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="IntAl003" INFO_INFO="Estado" MON_ADDRNUM="10059" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="LinAl017" INFO_INFO="Estado" MON_ADDRNUM="10060" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="LinAl511" INFO_INFO="Estado" MON_ADDRNUM="10061" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="IntAl435" INFO_INFO="Estado" MON_ADDRNUM="10062" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="BarAl414" INFO_INFO="Estado" MON_ADDRNUM="10063" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
<s104:SP INFO_B1="SCONTROL" INFO_B2="132" INFO_B3="MARTOS" INFO_ELEM="LinAl009" INFO_INFO="Estado" MON_ADDRNUM="10064" COM_TYPE="null" COM_ADDRNUM="0" PRO_GC="Y"></s104:SP>
